import type { Playbook } from '../data/playbooks';

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
}

function buildAuditChecklistMarkdown(pb: Playbook): string {
  const lines: string[] = [
    `# Audit Evidence Pack — ${pb.title}`,
    '',
    `**Generated:** ${new Date().toLocaleString()}`,
    `**Domain:** ${pb.domain} | **Difficulty:** ${pb.difficulty} | **Duration:** ${pb.estimatedDuration}`,
    '',
    '## Executive Summary',
    pb.overview,
    '',
    '## Business Case',
    pb.businessCase,
    '',
    '## Implementation Checklist',
    '',
  ];

  pb.phases.forEach((phase, idx) => {
    lines.push(`### Phase ${idx + 1}: ${phase.name} (${phase.duration})`);
    lines.push('');
    lines.push('#### Activities');
    phase.activities.forEach(a => lines.push(`- [ ] ${a}`));
    lines.push('');
    lines.push('#### Deliverables');
    phase.deliverables.forEach(d => lines.push(`- [ ] ${d}`));
    lines.push('');
    lines.push('#### Stakeholders');
    phase.stakeholders.forEach(s => lines.push(`- ${s}`));
    lines.push('');
    if (phase.riskFlags.length > 0) {
      lines.push('#### Risk Flags');
      phase.riskFlags.forEach(r => lines.push(`- ⚠ ${r}`));
      lines.push('');
    }
  });

  lines.push('## Key Metrics (KPIs)');
  pb.keyMetrics.forEach(m => lines.push(`- [ ] ${m}`));
  lines.push('');
  lines.push('## Maturity Model');
  pb.maturityLevels.forEach(ml => {
    lines.push(`- **L${ml.level} — ${ml.name}:** ${ml.criteria}`);
  });
  lines.push('');
  lines.push('## Exam Relevance');
  lines.push(pb.examRelevance);
  lines.push('');
  lines.push('## Real-World Example');
  lines.push(pb.realWorldExample);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by AAISM Study App — Implementation Playbooks*');

  return lines.join('\n');
}

function downloadBlob(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPlaybookMarkdownBundle(pb: Playbook): void {
  const md = buildAuditChecklistMarkdown(pb);
  downloadBlob(`audit-evidence-${slugify(pb.title)}.md`, md, 'text/markdown;charset=utf-8');
}

export function openPlaybookAuditPdf(pb: Playbook): void {
  const md = buildAuditChecklistMarkdown(pb);
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Audit Evidence — ${pb.title.replace(/</g, '&lt;')}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #111; line-height: 1.5; }
    h1 { font-size: 1.5rem; border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }
    h2 { font-size: 1.15rem; margin-top: 1.5rem; color: #1e40af; }
    h3 { font-size: 1rem; margin-top: 1rem; }
    h4 { font-size: 0.9rem; margin-top: 0.75rem; color: #374151; }
    ul { padding-left: 1.25rem; }
    li { margin: 0.25rem 0; }
    .meta { color: #6b7280; font-size: 0.875rem; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <pre style="white-space: pre-wrap; font-family: inherit;">${md.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
  <script>window.onload = () => { window.print(); };</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    downloadPlaybookMarkdownBundle(pb);
    return;
  }
  win.document.write(html);
  win.document.close();
}
