/** Auto-generated by scripts/sync-version.mjs — do not edit manually. */
export const APP_VERSION_SEMVER = '1.0.0';
export const APP_ICON_BADGE = 'dev+ef271b4';
export const APP_VERSION = '1.0.0-dev+ef271b4 (2026-06-20)';
export const APP_BUILD = 'ef271b4';
export const APP_BUILD_DATE = '2026-06-20';
export const APP_WINDOW_TITLE = 'Aegis · dev+ef271b4';
export const APP_PWA_NAME = 'Aegis dev+ef271b4';
