/** Auto-generated by scripts/sync-version.mjs — do not edit manually. */
export const APP_VERSION_SEMVER = '1.0.0';
export const APP_VERSION = '1.0.0-dev+78e712b (2026-06-19)';
export const APP_BUILD = '78e712b';
export const APP_BUILD_DATE = '2026-06-19';
export const APP_WINDOW_TITLE = 'Aegis · v1.0.0-dev+78e712b (2026-06-19)';
export const APP_PWA_NAME = 'Aegis v1.0.0-dev+78e712b (2026-06-19)';
