#!/usr/bin/env node
/**
 * Sync version metadata at build/dev start → appMeta.generated.ts
 * Format (dev): 1.0.0-dev+abc1234 (2025-06-19)
 * Format (release): 1.0.0+abc1234 (2025-06-19)
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { computeVersionInfo } from './lib/version-info.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const release = process.env.TAURI_RELEASE === '1' || process.env.RELEASE === '1';
const info = computeVersionInfo({ release });

const outPath = join(root, 'src/constants/appMeta.generated.ts');
const contents = `/** Auto-generated by scripts/sync-version.mjs — do not edit manually. */
export const APP_VERSION_SEMVER = '${info.semver}';
export const APP_VERSION = '${info.displayVersion}';
export const APP_BUILD = '${info.gitHash}';
export const APP_BUILD_DATE = '${info.buildDate}';
export const APP_WINDOW_TITLE = '${info.windowTitle}';
export const APP_PWA_NAME = '${info.pwaName}';
`;

writeFileSync(outPath, contents);
console.log(`[sync-version] ${info.displayVersion} · hash ${info.gitHash}`);
